### ISSUE TITLE
Add token support in <IzanamiProvider /> React component

### ISSUE THREAD

**Issue by gpoulet** [MAIF/izanami#114]
Hello,

I need a token props in <IzanamiProvider /> React Component like that :
```
import { getToken } from "./util/auth.js"

<IzanamiProvider fetchFrom="/api/izanami" token={ getToken() }>
    {/* your app */}  
  </IzanamiProvider>
```
Two benefits :
- Secure "/api/izanami" endpoint (in my app, all users need to be logged)
- Pass to Izanami Context users informations encoded in the token (clientId, roles, etc.) without Query Params (I need this params for "Script strategy" in Izanami Features).

**Comment by gpoulet** [comment]
After reading source code, I think that this should work :
```
import { getToken } from "./util/auth.js"

<IzanamiProvider fetchFrom="/api/izanami" fetchHeaders={{ Authorization: `Bearer ${getToken()}` }} >
    {/* your app */}  
  </IzanamiProvider>
```

I'll test tomorrow.

**Comment by larousso** [comment]
The best way to do that is that fetchFrom can take a string or a function. The function should be `() => Promise`

**Comment by gpoulet** [comment]
It doesn't work :(
