### ISSUE TITLE
Jdk 10 and ++

### ISSUE THREAD

**Issue by larousso** [MAIF/izanami#144]

**Comment by sorenvalentinjp** [comment]
Why was this issue closed?

**Comment by larousso** [comment]
Izanami is running with jdk 10 in production with redis and elastic. 

Did you get trouble running it with jdk 10 ? Reopen this issue if so.

**Comment by sorenvalentinjp** [comment]
Oh, nice. I thought the issue was closed because of obstructions, i am glad to hear it is working 👍 So the server is running with jdk 10 in the docker image on dockerhub?

**Comment by sorenvalentinjp** [comment]
Is it just the client that supports jdk 10? I see the Base image is jdk 8 for the server here https://github.com/MAIF/izanami/blob/master/izanami-server/build.sbt

`dockerBaseImage := "openjdk:8"`

**Comment by sorenvalentinjp** [comment]
The client works great on jdk 10 btw.

**Comment by SoerenValentinSilkjaer** [comment]
I created a pr for upgrading the server base image https://github.com/MAIF/izanami/pull/180
