### ISSUE TITLE
/health endpoint that does not require authentification

### ISSUE THREAD

**Issue by sorenvalentinjp** [MAIF/izanami#153]
We need a /health endpoint that does not require authentification in order to support self healing in docker orchestration services like Kubernetes, ECS etc.

Maybe reuse the /api/_health endpoint from https://github.com/MAIF/izanami/pull/149/files
we could just change the AuthAction in HealthCheckController into an Action, which would remove the need for authentification.

**Comment by larousso** [comment]
@sorenvalentinjp you can now use the env variable `FILTER_EXLUSION=/api/_health` to exclude the health api.
