### ISSUE TITLE
Appels HTTP en erreur avec Play! Scala avec la version 1.0.9

### ISSUE THREAD

**Issue by guillaumesolderaserli** [MAIF/izanami#194]
Quand on essaie de récupérer les features, on a l'erreur suivante
```
[error] a.a.ActorSystemImpl - Error during call, recovering ...
akka.stream.StreamTcpException: Connection failed.
```

Pas de soucis avec Izanami-1.0.4

Versions: 
 * sbt : 1.2.1
 * Scala : 2.12.6
 * Play : 2.6.18
 * Izanami-client : 1.0.9

**Comment by larousso** [comment]
The server and client have the same version ?

**Comment by guillaumesolderaserli** [comment]
After many tests, the error is appeared in 1.0.7 version.
With comparison between 1.0.6 and 1.0.7 tags (https://github.com/MAIF/izanami/compare/v1.0.6...v1.0.7) some versions have been updated but if I override versions with previous, I still have the error.
The comparison shows an update on `izanami-clients/jvm/src/main/resources/reference.conf` file with an `akka.http` conf. Can it cause some troubles or conflicts ?
Maybe this configuration should be scoped to izanami ?

**Comment by larousso** [comment]
@guillaumesolderaserli if you install the client locally with this config removed does it work ?
