### ISSUE TITLE
Feature toggling in React

### ISSUE THREAD

**Issue by yuriron** [MAIF/izanami#238]
I succeeded to fetch feature toggling values in my backend Play! project, but having difficulties to do it in my React  client project. The documentation just mentions that there is a requirement for a proxy, but it's not explained well. Could you please share a link with proper explanation regarding proxy and react client?

Here is my react code. I am getting only the disabled part.

    <IzanamiProvider fetchFrom="http://localhost:9001/api/izanami">

            <Feature path="ExtendedGreeting">

              <Enabled>

                <div>Enabled</div>

              </Enabled>

              <Disabled>

                <div>Disabled</div>

              </Disabled>

            </Feature>

    </IzanamiProvider>

**Comment by larousso** [comment]
Hi, you can find example applications in the example folder. 

The part for the proxy is here 
https://github.com/MAIF/izanami/blob/master/example/example-play/app/controllers/IzanamiController.scala

The config of the react app is here 
https://github.com/MAIF/izanami/blob/master/example/javascript-react/src/index.js#L98-L111

And the usage of the component : 
https://github.com/MAIF/izanami/blob/master/example/javascript-react/src/pages/TvShow.js#L100-L119

**Comment by yuriron** [comment]
I created a proxy that gets from my react client required data, passes it to Izanami and replies to client with feature flag value like this:
`{ExtendedGreeting:{active:true}}`
but it still shows only disabled value

**Comment by yuriron** [comment]
It didn't work since the client expects response like this:
    `{"features":{"ExtendedGreeting":{"active":false}}}`
