### ISSUE TITLE
Error when building with gatsby using react-izanami

### ISSUE THREAD

**Issue by charlyx** [MAIF/izanami#246]
Hi 👋 

We're experiencing a problem when building our website with gatsby.
Here is the error we get: 

> 54 | function _setPrototypeOf(o, p) { _setPrototypeOf = Object.setPrototypeOf || function _setPrototypeOf(o, p) { o.__proto__ = p; return o; }; return _setPrototypeOf(o, p); }
>   55 | 
> > 56 | if (!window.Symbol) {
>      | ^
>   57 |   window.Symbol = _esSymbol.default;
>   58 | }
>   59 | 
> 
> 
>   WebpackError: ReferenceError: window is not defined

That could be fixed using [globalThis](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/globalThis) instead of `window`.
As `globalThis` support is not good enough for now we'd need to use a polyfill such as [@ungap/global-this](https://github.com/ungap/global-this).

@frinyvonnick and I are willing to open a PR if that's OK 😄 

We'll first fork your project so we can fix it and test it on our project first.

What do you think?

**Comment by larousso** [comment]
You can open a PR, that could be great !
