### ISSUE TITLE
Bintray release link for 1.4.3 is broken

### ISSUE THREAD

**Issue by cbm-tlasalle** [MAIF/izanami#262]
Hello,

When you released 1.4.3 on bintray, it seems that your release process missed a variable replacement ; when you go on the [binary download page](https://dl.bintray.com/maif/binaries/izanami-dist/), you can see that the 1.4.3 version is not present but a mysterious $BINARIES_VERSION is (and it contains the 1.4.3 version).

**Comment by larousso** [comment]
Hi, could you try again. I think I have fixed the problem

**Comment by cbm-tlasalle** [comment]
Hi, this is fixed, nice work :+1:
