### ISSUE TITLE
Uncaught ReferenceError: Izanami is not defined 1.4.3

### ISSUE THREAD

**Issue by cbm-saziri** [MAIF/izanami#264]
Hello,

When I try to run izanami-dist.zip from version 1.4.3, I have the following error from the front: 

Uncaught ReferenceError: Izanami is not defined

So I can't get the front site anymore. 

Thank you.

**Comment by larousso** [comment]
Hi, 
We had some issues with our bintray account so I build release manually. The build seems broken, I will try to republish the zip and the binarie today

**Comment by cbm-saziri** [comment]
Thank you for you quick reply. I will wait for the new release then 👍

**Comment by larousso** [comment]
Hi, I have published the binaries again, could you try and tell me if it is ok ?

**Comment by cbm-saziri** [comment]
Ok thank you it's working like a charm 👏
