### ISSUE TITLE
db namespace change from ":" to "_" in dynamoDB in 1.5.0

### ISSUE THREAD

**Issue by cbm-saziri** [MAIF/izanami#283]
Hello, 

Since we upgrade from Izanami 1.4.3 to 1.5.0, namespaces changed from ":" to "_"
It means features, users ... are not visible from the interface now. 
Exemple in database: 

Before : izanami:feature
Now : izanami_feature

We keep using ":" in the configuration file though : 
`features {
    db {
      type = ${izanami.db.default}
      type = ${?FEATURE_DATABASE}
      import = ${?FEATURE_IMPORT}
      conf {
        namespace = ${izanami.namespace}":features"
        namespace = ${?FEATURE_NAMESPACE}
      }
    }
  }`

Thank you and good luck.

**Comment by larousso** [comment]
Sorry it's a mistake, I will revert this behavior in the next release

**Comment by cbm-saziri** [comment]
Thank you, let me know when it's ready :)

**Comment by larousso** [comment]
@cbm-saziri I've just released the 1.5.1 version to fix the problem. 
You can try and reopen this issue if the problem persists

**Comment by cbm-saziri** [comment]
Ok thank you for your reactivity, it's working now ! I let you know if I found something else later. 
And congrats for the new features 👏
