### ISSUE TITLE
IHM - Group by feature name doesn't work anymore

### ISSUE THREAD

**Issue by cbm-saziri** [MAIF/izanami#291]
Hello,

Since we upgrade to 1.5.1 version, group by features stop working. 

Thank you

**Comment by larousso** [comment]
Hi, could you be more precise ? 
group by feature on the ui ? On the API ? 
I have just fixed something on the UI, where updates dont refresh the datas in the UI. Is it the problem ?

**Comment by cbm-saziri** [comment]
Hello,

I'am talking about a bug on the ui only. When I click on the "Switch the view" button, all features disappear. Maybe is the same you fixe, you tell me ? 

Thank you !

**Comment by larousso** [comment]
I don't reproduce this one. Could you tell me, what is your DB ? what is your event store ?
Do you have any error on the console of the browser ? 
What is you browser ? 
Thanks

**Comment by cbm-saziri** [comment]
Hello,
So we are using dynamoDB. 
When I click to "Switch the view" i got a 500 response code from : 
api/features?pattern=**&render=tree

It's working with version 1.4.3 but not with this one

thank you!

**Comment by larousso** [comment]
I don't reproduce this issue. Do you have any logs on the server ? 
Tree view needs to load all features in memory, do you have a lot of feature that could end with an OOM ?

**Comment by cbm-saziri** [comment]
Hello, 
Thank you for your assistance. I upgrade to 1.5.2 and it's seems to work, I don't have the error anymore. I'm closing the ticket.

**Comment by larousso** [comment]
Fine !
