### ISSUE TITLE
[BUG] AutoCreate feature does not work when using fetchWithCacheStrategy

### ISSUE THREAD

**Issue by sorenvalentinjp** [MAIF/izanami#295]
First of all, thank you for  this awesome piece of software!

Features are not being created automatically when autocreate is enabled and the client is using fetchWithCacheStrategy.

Autocreate seems to work when running the client with any other strategy.

I am using the scala client and tried with Redis and InMemory as store.

**Comment by larousso** [comment]
Hi,
Are the features present in your fallback ?

**Comment by sorenvalentinjp** [comment]
Hi. I will try again and double check that my setup is not flawed.

**Comment by sorenvalentinjp** [comment]
Hi again.
I tried again and double checked that everything is right. I cannot make it work with the fetchWithCacheStrategy. If I just change the strategy parameter when instantiating the izanami feature client to another strategy like fetchStrategy, it works immediately.
