### ISSUE TITLE
[Question] Scaling izanami

### ISSUE THREAD

**Issue by sorenvalentinjp** [MAIF/izanami#299]
Does anyone have experience scaling izanami? Particularly running multiple izanami instances in a cluster and running the stores in a cluster? Should it work out of the box?

**Comment by larousso** [comment]
Hi, 
You can scale Izanami but : 
 * you need kafka or redis as event store if you use events ie with a swartCache strategy 
 * you need to use a db that could be shared (any db except in memory and leveldb)
