### ISSUE TITLE
Multi-environment support

### ISSUE THREAD

**Issue by cwoodrow** [MAIF/izanami#312]
What would be the best solution to implement multi-environments support ? 

For example : create new feature (or delete existing one) into dev environment, then "promote" it through the successive environments. 

Current solutions to do that which I think are not satisfying are : 
- copy manually in with tree view
- use import / export 

A few solutions that could do the trick : 
- provide directly the feature, which is I think not really our purpose because we want Izanami usage to be the 
- provide more features on import / export 

@julienbourgoin What do you think ?

**Comment by sorenvalentinjp** [comment]
If you are using the JVM client you can enable autocreate to autocreate features or configs from fallback if they do not exist on the server.
https://maif.github.io/izanami/manual/clients/jvm.html#autocreate-features
