### ISSUE TITLE
[React] Izanami Feature component unexpected behavior

### ISSUE THREAD

**Issue by kefranabg** [MAIF/izanami#323]
Hi 👋

First thanks for your work 👍

## Describe the bug

I encountered a problem while using `IzanamiProvider` with `fetchFrom` and `Feature` component with `Enabled` and `Disabled` components as children.

The Izanami `Feature` renders `Disabled` content until the `fetchFrom` promise is resolved. IMHO, `Feature` component should not render anything until it receives the Izanami features state.

## Steps to reproduce

```
 <IzanamiProvider
          id = "izanamiProvider"
          fetchFrom={() =>
              fetch("/api/izanami", {
                  method: 'GET',
                  credentials: 'include'                
              })
          }>
    {/* my app */}    
  </IzanamiProvider>
```

```
<Feature path="izanami.my.feature">
  <Enabled>
    {/* enabled component */}    
  </Enabled>
  <Disabled>
    {/* disabled component */}    
  </Disabled>
</Feature>
```

## What is expected

`Feature` component should not render anything until the `fetchFrom` promise is resolved.

## What is actually happening?

`Disabled` content is rendered until my `fetchFrom` request is done.

**I can make a PR if you want.**

**Comment by larousso** [comment]
Hi, thanks for the report! 

A PR is welcomed if you have an idea to fix this issue !
