### ISSUE TITLE
Versioning of Shared Configuration

### ISSUE THREAD

**Issue by madslyng** [MAIF/izanami#344]
As a developer allowing business people to edit application configuration via Shared Configuration, I would like to be able to switch between versions of shared configuration state, so that there is less risk involved with allowing business people to maintain shared configuration.

**Comment by larousso** [comment]
At the moment you can do this with the name of the config: 
`my:config:v1` to `my:config:v2`

I will try to develop something on this, but it needs some deep refactoring so it could take some time.
