### ISSUE TITLE
[Question] Any way to check if the client has a connection?

### ISSUE THREAD

**Issue by ndlarsen** [MAIF/izanami#350]
Hi.

First of all, I apologize in advance if this is not the proper place to ask questions.

Now, in a Scala project of ours we have an izanami client (configured with the smartCacheWithPollingStrategy but this should be irrelevant). For monitoring purposes we would like to check if the client is actually able to establish a connection at any given time. The thought is something like this:
```scala
def doHeartbeat(): Future[Type] = {
   // check if izanami client can connect
   if (izanamiClient.canConnect()) {
       // YAY!
   } else {
      // somehow trigger alert
   }
}
```

I have been looking though the client related code + documentation and while it is likely I have missed it, I have not found any indication that such functionality exists.
In case I have missed something could you please direct me to the proper location? If I have not missed anything, do you have any suggestions on how this could be solved without wrapping the client library?

Cheers

**Comment by larousso** [comment]
Hi, at the moment nothing exists for this but I could add something to test the connectivity. 
Is it something that you would run periodically or only when your app is starting ?

**Comment by ndlarsen** [comment]
Appreciate your reply.
That would be truly great. In this case we were talking about adding the call to our health controller so the check is made every time the health endpoint is called if possible. Essentially we are just missing a "ping izanami server with current configuration" method.

**Comment by ndlarsen** [comment]
Is there anything I can do to expedite this?

**Comment by larousso** [comment]
Hi, sorry for the delay, I opened a PR that I have not tested yet. 
I will work on Izanami next week.

**Comment by larousso** [comment]
Ok I've tested it, i will merge it soon and I can do a release after

**Comment by larousso** [comment]
@ndlarsen a `1.7.2`has been published and there is an `healthCheck()` method available on the `IzanamiClient`

**Comment by ndlarsen** [comment]
This is excellent news. Thank you very much.
