### ISSUE TITLE
Php client 

### ISSUE THREAD

**Issue by larousso** [MAIF/izanami#36]
Create a php client

**Comment by cwoodrow** [comment]
Client needs to be able to handle cache, related to @Freyskeyd's problem on https://gitter.im/MAIF/izanami

**Comment by cwoodrow** [comment]
@ptitFicus ?

**Comment by LeJeanbono** [comment]
A symfony bundle is acceptable ?

**Comment by larousso** [comment]
@LeJeanbono At the moment nobody is doing php on our team so any contribution is welcomed :)
