### ISSUE TITLE
Release plan unclear—is scala 2.12 still supported?

### ISSUE THREAD

**Issue by jonaskoelker-jypo** [MAIF/izanami#372]
I would like to perform a healthCheck (see issue #350) in my app, which is built with Scala 2.12.

I looked around the internet but found no izanami-client_2.12-1.7.2 or anything of the sort. Do you plan on releasing a build for Scala v2.12?

I can build and run git head for Scala v2.12, but I would greatly prefer downloading an official package.

Is there anything I can do to help you support Scala v2.12? If you let me know, I promise to at least seriously consider doing it :-)

I think I'm not the only one who would appreciate a version compatibility table in the readme and a short paragraph on planned future (in)compatibility; one that would've answered my question.

**Comment by larousso** [comment]
Hi, 

the client is available here: 
https://bintray.com/maif/maven/izanami-client?tab=overview

There's only a 2.13 version at the moment but this is a release issue. 
The goal was to publish a 2.12 and a 2.13 version but it fails. 

I will try to fix it as soon as possible.

**Comment by larousso** [comment]
@jonaskoelker-jypo  This should be fixed

**Comment by jonaskoelker-jypo** [comment]
I've successfully bumped the izanami client version number in my `build.sbt` to 1.7.2 and called the `healthCheck()` method. Thank you for the fix, and I'm impressed by your quick response time! :+1:

**Comment by larousso** [comment]
You're welcome! I close this issue
