### ISSUE TITLE
[Error] experiment variants

### ISSUE THREAD

**Issue by Johan-Pedersen** [MAIF/izanami#429]
When I tried to add more than 2 variants to my experiment, the amount of client id's I could choose from got smaller and smaller. (I use int)

The method I used: experimentClient.getVariantFor("experimentId", "clientId")

Data:
with 2 variants I could choose every number as client id (I tried from -100 up to100).
with 3 variants I could choose from client id -1to 2.
with 4 variants I could only use the client id 0. 

The error I got when the client id was out of range was NoSuchElementException.

**Comment by SoerenSilkjaer** [comment]
I believe this was with the scala dsl.

**Comment by pierrebruninmaif** [comment]
I don't reproduce exactly your issue. But i fixed a major issue when there are more than 2 variants.
If you still encounter the problem with version 1.8.3, reopen this issue and give me more details to reproduce it.
