### ISSUE TITLE
Lock feature path

### ISSUE THREAD

**Issue by larousso** [MAIF/izanami#494]
Add the ability to "lock" a path for features. 

As an admin I could set a lock on a path 
As a user I could only create a feature as a leaf of the lock path 

E: 
if I have a lock on `mytvshow:ui` 
I can create 
* a feature with key `mytvshow:ui:feature1` 
* or `mytvshow:otherui:feature1` 
* but I can't create  `mytvshow:feature1`.

**Comment by pierrebruninmaif** [comment]
Fix 1.10.1
