### ISSUE TITLE
HomePage, error in console

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/izanami#558]
react-dom.development.js:506 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in HomePage (created by component)
    in component (created by Route)

It seems to be here :
  componentDidMount() {
    ...
    this.update();
  }

**Comment by pierrebruninmaif** [comment]
Fix 1.10.1
