### ISSUE TITLE
Warning: Each child in an array or iterator should have a unique "key" prop.

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/izanami#560]
When I want to "Create a Configuration" without "Configuration Id"
-> error

configurations/add

react_devtools_backend.js:2560 Warning: Each child in an array or iterator should have a unique "key" prop.

Check the render method of `FieldError`. See https://fb.me/react-warning-keys for more information.
    in div (created by FieldError)
    in FieldError (created by Form)
    in div (created by Form)
    in form (created by Form)
    in Form (created by Table)
    in div (created by Table)
    in div (created by Table)
    in Table (created by ConfigurationsPage)
    in div (created by ConfigurationsPage)
    in div (created by ConfigurationsPage)
    in ConfigurationsPage (created by component)
    in component (created by Route)
    in Route (created by LoggedApp)
    in Switch (created by LoggedApp)
    in div (created by LoggedApp)
    in div (created by LoggedApp)
    in div (created by LoggedApp)
    in div (created by LoggedApp)
    in div (created by LoggedApp)
    in div (created by LoggedApp)
    in div (created by LoggedApp)
    in LoggedApp (created by Route)
    in Route (created by PrivateRoute)
    in PrivateRoute (created by IzanamiApp)
    in Switch (created by IzanamiApp)
    in IzanamiApp (created by Route)
    in Route (created by withRouter(IzanamiApp))
    in withRouter(IzanamiApp) (created by RoutedIzanamiApp)
    in Router (created by RoutedIzanamiApp)
    in RoutedIzanamiApp****

**Comment by pierrebruninmaif** [comment]
Fix 1.10.1
