### ISSUE TITLE
[Feature Flipping] Feature toggle is getting deleted after updation when used with Cassandra

### ISSUE THREAD

**Issue by Sarangk90** [MAIF/izanami#60]
HI Folks,

I was trying out Izanami integration with Cassandra. It looks like whenever we update a feature toggle, it actually gets deleted. 

**Steps to reproduce:**
1. Create a feature toggle. 
2. Click on edit to edit the FT.
3. Change the strategy and hit update
4. Refresh the page 

Thanks,
Sarang...

**Comment by larousso** [comment]
Hi @Sarangk90, I didn't reproduce this issue. Which version of Izanami are you using ? 

If you're using docker, try to get the latest image to be sure that you get this problem.
