### ISSUE TITLE
Izanami client library compatibilty with Java 8

### ISSUE THREAD

**Issue by denisboisteux** [MAIF/izanami#601]
Hi ! Can you confirm that there is currently no alternative for integration on a Java 8 application?
If so, would it be possible to make a compatible version available?

**Comment by pierrebruninmaif** [comment]
Hi Denis, the Java clients are now compatible with Java 8. This compatibility will be maintained until the end of Java 8 support (3/2022) and / or the introduction of code / lib not compatible with Java 8.

**Comment by denisboisteux** [comment]
Thanks for posting this release quickly
