### ISSUE TITLE
Add confirmation popup before changing a feature state

### ISSUE THREAD

**Issue by julienbourgoin** [MAIF/izanami#603]
Hi,
It would be nice if, when in the main feature menu and we click on the pink bouton to change a feature state, a confirmation popup appears before the action is effectively done. The popup should mention the feature name, so we can double check what we are doing.

In the detail screen of a specific feature, you have to click on the "Update feature" button to make effective the state change.

**Comment by pierrebruninmaif** [comment]
You need to set a envvar to enable this feature : https://maif.github.io/izanami/manual/settings/settings.html#ui
