### ISSUE TITLE
[Bug] [User Creation UI] While creating new user, the newly created user gets displayed twice in UI

### ISSUE THREAD

**Issue by Sarangk90** [MAIF/izanami#63]
Hi Team,

While creating new user, the newly created user gets displayed twice in UI, however the database reflects correct information.

Also, there are no validation on any field, This might cause a security concern.

Thanks,
Sarang...

**Comment by ksarang90** [comment]
Thanks a lot @larousso 
Should I expect this in v1.0.3 release ?

**Comment by larousso** [comment]
Sure, it will be on the next release !
