### ISSUE TITLE
Vue.js client

### ISSUE THREAD

**Issue by ghost** [MAIF/izanami#64]

**Comment by dlecan** [comment]
I consider choosing Izanami, but I have Vue.js apps in the scope.
What is the state of this enhancement?

**Comment by rl-hire** [comment]
Hi, do you plan to create a vue.js client soon ?
As dlecan, we are using vue and considering to use izanami

**Comment by pierrebruninmaif** [comment]
Hi, we don't have a plan to create vue.js, because we don't have skill in Vue.js. 
But you have some developpers in Vue.js, if you are interested, you can contribute.

**Comment by rl-hire** [comment]
Haha I was guessing that and was thinking it could be great to do so.
By the way, I really like your OSS repos ans was a bit surprised to find this by Maif !
Very nice surprise ;)

**Comment by pierrebruninmaif** [comment]
don't try to flatter us, we will not developpe the client ;-) 
Thank's for your feedback !!
