### ISSUE TITLE
Add documentation on DockerHub

### ISSUE THREAD

**Issue by SIPR-octo** [MAIF/izanami#648]
Hello there :wave: 

There is currently no documentation at all on your DockerHub image page, which makes it difficult to find the corresponding Dockerfile: https://hub.docker.com/r/maif/izanami

That would be great if you could add some, thanks!

**Comment by pierrebruninmaif** [comment]
Hello @SIPR-octo, [GitHub](https://github.com/MAIF/izanami) and [DockerHub](https://hub.docker.com/r/maif/izanami) have now a same homepage
