### ISSUE TITLE
Critical vulnerabilities in Docker image for version 1.10.7

### ISSUE THREAD

**Issue by SIPR-octo** [MAIF/izanami#661]
Hi! :wave: 

There are some critical vulnerabilities in your latest Docker image (version 1.10.17) which are already patched.
Note that there were no updates on your Docker images for 2 months now.

See trivy scan results below:

![image](https://user-images.githubusercontent.com/82641199/173311431-2a3bca0c-9183-41d0-9729-3b8df3ef10f5.png)

Would it be possible to update your images? :pray: 

(similar to my previous issue https://github.com/MAIF/izanami/issues/649)

**Comment by TACY-octo** [comment]
Hello @pierrebruninmaif, do you have a few time to help us on issue (Can you update the base image of izanami / create release) ? 🙏

**Comment by desmfr** [comment]
i assigned @ptitFicus on the issue ;)

sorry for

**Comment by SIPR-octo** [comment]
It worked, thanks a lot! :pray:
