### ISSUE TITLE
about redis store configuration

### ISSUE THREAD

**Issue by fsamin** [MAIF/izanami#70]
Hi guys ✋ 

It could be nice to be able to: 
* setup redis database ID (0 by default) in server configuration 
* set a prefix for all keys in server configuration, to have redis keys like `izanami:project:env:feature1`

Does it supports redis sentinels ? Could you provide an example of such a configuration ?

**Comment by larousso** [comment]
Hi, 
At the moment there is no support to use redis database. I will add this very soon. 

Concerning the prefix for keys, there is a prefix set by "domain" with the key `izanami.{namespace}.db.conf.namespace`. 
For example `izanami.config.db.conf.namespace=izanami:configuration`, you can use the `CONFIG_NAMESPACE` env var to set this value too. 
There is no global prefix for keys, you have to set this for all keys. It's to define one so I can implement this quickly.  

Concerning the sentinel, it's not supported at the moment, i will add the support very soon too.

**Comment by larousso** [comment]
Related to #73 #72 #71

**Comment by fsamin** [comment]
Thanks for your answers, i will follow those 3 issues and close this one
