### ISSUE TITLE
Experiment report very slow with millions of events

### ISSUE THREAD

**Issue by SoerenSilkjaer** [MAIF/izanami#706]
Generating an experiment report in the UI is very slow when there are millions of events.

The problem seems to be that the experiment [results endpoint](https://github.com/MAIF/izanami/blob/bae607bc1d9fa1da2aa00f8e92be1d33c6b25b6b/izanami-server/app/controllers/ExperimentController.scala#L227) is extracting every single event that happened on the experiment, and iterates over them in memory. With just a few thousand experiment events, this becomes a very expensive operation.

First solution that comes to mind is to use the database/store to aggregate the results.

**Comment by SoerenSilkjaer** [comment]
I can contribute with a pr if we can agree on a solution.

**Comment by SoerenSilkjaer** [comment]
#707

**Comment by pierrebruninmaif** [comment]
Hi @SoerenSilkjaer, i hope to work on this issue next week. But your help is welcome. 
As you mention, all events are fetching in memory. I also suspect a huge usage of threads, leading some locks.
