### ISSUE TITLE
Omnisearch in front

### ISSUE THREAD

**Issue by ptitFicus** [MAIF/izanami#769]
The idea is to have a search bar present in Izanami topbar.

Search should display a result box as you type, that indicates search results.

Search should search among : 

- Features
- Projects
- Tags
- Tenants
- Api Keys
- Webhooks
- Users

When clicking on a result entity that does not have a dedicated page, for instance a feature, we should display a page when resulting entoty is visible (for feature it should be project page) and either highlight feature or filter feature table to keep only resulting feature visible.

**Comment by helakaraa** [comment]
![DiagrammeOmni](https://github.com/MAIF/izanami/assets/10269106/2c2506f7-592c-454f-9c16-724fa7132560)
