### ISSUE TITLE
Maven java client - 1.11.5 - CVE AKKA ACTOR

### ISSUE THREAD

**Issue by soleanos** [MAIF/izanami#798]
Bonjour, 

Nous constatons qu'il y a une CVE dans le client JAVA d'izanami, pourriez vous svp la corriger ? 
Nous souhaitons prendre un peu de temps et de recul avant de passer sur la V2. 
Merci par avance

![image](https://github.com/MAIF/izanami/assets/16062742/3e39d8dd-cfb2-4462-ba88-5470b9ac2618)![image](https://github.com/MAIF/izanami/assets/16062742/01a6987d-7072-4048-8a57-18902a42be2c)

**Comment by ptitFicus** [comment]
Bonjour @soleanos !

Merci pour le signalement, j'essaye de faire ça dans les prochains jours.

**Comment by ptitFicus** [comment]
Bonjour @soleanos,

La version 1.11.7 est relasée avec une monté de version de akka-http qui devrait régler le souci.
Je ferme cette issue, n'hésite pas à en rouvrir une en cas de besoin.

Bonne journée
