### ISSUE TITLE
Feature enabled is not highlighted anymore on project page

### ISSUE THREAD

**Issue by ptitFicus** [MAIF/izanami#804]
Before : 

<img width="170" alt="image" src="https://github.com/MAIF/izanami/assets/1528358/67de8449-838f-4f12-99b4-01014479e71e">

After : 

<img width="156" alt="image" src="https://github.com/MAIF/izanami/assets/1528358/8d81f0d9-d871-44dd-bd9b-6a18492b0667">

**Comment by baudelotphilippe** [comment]
That's true :D

By the way, we can filter the column by status, is it mandatory to add a color to give attention to the enabled features ?

**Comment by ptitFicus** [comment]
I think it may be relevant to use a special highlight for this column, since if the feature is disabled everything else on the rows doesn't really matter. Perhaps we could represent this another way, for instance by giving a "disabled appearence" to disabled rows ?
