### ISSUE TITLE
to be undefined or no to be undefined

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/izanami#808]
If I try to create a New feature without selected a project, there is an error message
<img width="836" alt="image" src="https://github.com/MAIF/izanami/assets/27761959/90edb78d-8ed9-43a8-b7a1-5f1039a232fd">

That's right but if I create a Project named "undefined" (:D) and I retry to create a feature, this time there is no error and the New feature is automatically add to the undefined Project.

<img width="836" alt="image" src="https://github.com/MAIF/izanami/assets/27761959/f32501a5-6789-4a5f-a5f2-b9d64cfdb82c">

Is it a bug or a feature ?

**Comment by ptitFicus** [comment]
Nice one, fixed by preventing form validation while project field is empty.
