### ISSUE TITLE
Allow to copy another user rights for a new user

### ISSUE THREAD

**Issue by ptitFicus** [MAIF/izanami#817]
Home/User/ **Invite New User** form : we need to enhance the user invitation process by allowing the assignment of rights from an existing user to the newly invited user. Therefore, we should add a new select button **Copy User Rights** that allow us to select an existing user.

**Comment by helakaraa** [comment]
### Cases  "Test User Invitation"
- [x]  Create a user from a copy-rights-only user with no rights but add tenant rights.
- [x]  Create a user from a copy-rights-only user but with no rights.
- [x]  Create a user with full permissions.
- [x]  Create a user with both copy rights and tenant rights(if copied rights contains the same tenant rights, we keep the tenant rights)
- [x]  Create a user with tenant rights only.
- [x]  Create a user with copy rights only.
- [x]  Create a user with no rights but as an admin.
- [x]  Create a user with no rights.
