### ISSUE TITLE
Add a Microsoft Teams connector in addition to webhook

### ISSUE THREAD

**Issue by julienbourgoin-maif** [MAIF/izanami#820]

**Comment by ptitFicus** [comment]
See [this link](https://learn.microsoft.com/fr-fr/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook?tabs=newteams%2Cdotnet) for specific teams use case.

A perfect solution would be to allow customizing webhook body (with template + some sort of variable interpolation) to be able to handle any specific webhook need easily.
