### ISSUE TITLE
error on deleting a context

### ISSUE THREAD

**Issue by nayosis** [MAIF/izanami#825]
When deleting a context in the application, the error "context doesn't exist" appears.

It seems that the construction of the endpoint is incorrect, with a double "/" in the API:

http://localhost:9000/api/admin/tenants/maifvie-tapc/projects/a2p/contexts//env52

Version used : https://github.com/MAIF/izanami/releases/tag/v2.1.0

**Comment by ptitFicus** [comment]
Thanks for reporting this, looks like it's fixed already.

It'll ship with next release !

**Comment by nayosis** [comment]
🙏
