### ISSUE TITLE
hardcoded url for oidc button on login page

### ISSUE THREAD

**Issue by keltakmaster** [MAIF/izanami#826]
I tried to deploy the software with openid connect, but despite my efforts to configure the variables, I found out that this line:

https://github.com/MAIF/izanami/blob/073351ded067b752ff5032ffc45759fb542551eb/izanami-frontend/src/pages/login.tsx#L168

always takes precedence when I click on the "openid connect" button on the login page.

Shouldn't it use the env var "IZANAMI_EXPOSITION_URL"?

Cheers.

**Comment by ptitFicus** [comment]
Hi,

Good catch thanks !

I'll release a fix in upcoming days.

Cheers
