### ISSUE TITLE
Remove the Search project filter when there is no project

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/izanami#838]
<img width="1215" alt="image" src="https://github.com/MAIF/izanami/assets/27761959/220f66de-5ee1-448e-81be-f00ac9546943">

**Comment by ptitFicus** [comment]
Perhaps once https://github.com/MAIF/izanami/pull/841 will be merge we could remove this search field ?


What do you think ?

**Comment by baudelotphilippe** [comment]
yes ! (if the search search ;))

**Comment by helakaraa** [comment]
I did change this in the search field branch
