### ISSUE TITLE
Error message appears on login form just before oidc redirection

### ISSUE THREAD

**Issue by ptitFicus** [MAIF/izanami#849]
When clicking on OpenIdConnect button on login page, the form shows briefly an error just before redirection.
It would be nice to make this error message disapear.

**Comment by helakaraa** [comment]
We need to hide this error message, if we click on **OpenId connect** : 
![Capture d’écran 2024-10-22 à 15 45 52](https://github.com/user-attachments/assets/e919087b-2e92-40c4-bc55-e6e3668f1877)
