### ISSUE TITLE
Improve Search

### ISSUE THREAD

**Issue by ptitFicus** [MAIF/izanami#857]
- [x]  Show search history (Save history in localStorage : create history by user)
- [x] Allow to search only in 1 category (project, feature, ...)
- [x] Make search value parametric from config
- [ ] Allow to browse search results with directional keys / select them with enter 
- [x] Recall search query if we change tenants or filters

**Comment by helakaraa** [comment]
**First Mockup vision :** 
<img width="1057" alt="Capture d’écran 2024-09-27 à 10 33 50" src="https://github.com/user-attachments/assets/d4394aa5-c2f6-4c2b-934d-92bf6a233001">

**Comment by helakaraa** [comment]
For the Search modal on the home page, we need to add an "All Tenants" button, a tenant selector to choose the desired tenant, and a filter selector to match the visual layout of the search modal in a specific tenant.
<img width="793" alt="Capture d’écran 2024-10-22 à 13 37 07" src="https://github.com/user-attachments/assets/b41894ce-daee-409a-893b-82034eddc6f4">

**Comment by helakaraa** [comment]
### Review Search Bar with Team:
<img width="830" alt="Capture d’écran 2024-11-05 à 09 50 38" src="https://github.com/user-attachments/assets/e4923755-8dbc-4561-8647-955085207064">

- [ ]  Display recently searched terms when the search modal opens. Once the user begins typing, hide the recent searches and show only the search results.
- [ ]  If a filter is selected before searching, apply it to recent searches as well. Retain a minimum of 30 items in the SearchHistory.
- [ ]  Add icons to the filter options.

 <img width="810" alt="Capture d’écran 2024-11-05 à 10 20 50" src="https://github.com/user-attachments/assets/8bf7c99f-cdce-444f-9078-027a7bbbcecf">

- [ ]  Ensure the design of recent search items matches that of search results.
- [ ] For this version, no need to add  "Allow to browse search results with directional keys / select them with enter" .
