### ISSUE TITLE
Custom Base URL

### ISSUE THREAD

**Issue by sguiheux** [MAIF/izanami#86]
Hi, 
Need this feature:
Add the possibility to specify a base url, to deploy izanami under a custom path.
For example:  https://host/toto/izanami

Need to set this env variable during docker run .

**Comment by larousso** [comment]
Hi @sguiheux, 
you can try this java property: `play.http.context`. 
This configuration is not exposed as env variable at the moment but I can add it easily.

**Comment by sguiheux** [comment]
Hi, already tried with this , but it does not work.
Problem seems to be on react side. ( but not sure, i'm not an expert on reactneither playframework )
