### ISSUE TITLE
💡 Docker image: build multiplatform

### ISSUE THREAD

**Issue by jeanphi-baconnais** [MAIF/izanami#861]
Hello 👋 

On Docker Hub I saw you have only amd plateform supported on your Docker image.

The GitHub action offers the possibility to add this attribute `platforms: linux/amd64,linux/arm64`. 

Is there any reason to build only for amd platform ? or if you want, I can prepare a PR with this modification.

**Comment by ptitFicus** [comment]
Hi :)

Good catch, there is no reason for this.

I would be happy to merge a PR on this, otherwise I'll look into it next week.

Best regards

**Comment by ptitFicus** [comment]
Looks like your PR did the trick : 2.5.0 exists with two architectures : https://hub.docker.com/r/maif/izanami/tags

I close this, don't hesitate to open a new issue if something is wrong with generated images.

**Comment by jeanphi-baconnais** [comment]
Hello, yes great ! And it's works on my mac on ARM 👍
