### ISSUE TITLE
Give informations for Anonymous reporting in Global settings

### ISSUE THREAD

**Issue by baudelotphilippe** [MAIF/izanami#886]
Maybe it would a good idea to explain what, when, and so on here (like the content displayed during the first connection)

<img width="621" alt="image" src="https://github.com/user-attachments/assets/a26289e2-8bb0-49cd-b0fc-e33f6c277c82">

**Comment by helakaraa** [comment]
Display a message stating:  "This feature allow Izanami to send us periodical reports. It won't send sensitive or personnal data, only a set of usage statistics related to Izanami {see details of the data sent below}  {..}" between the **Anonymous reporting** label and the toggle button.
![Capture d’écran 2024-10-22 à 16 13 57](https://github.com/user-attachments/assets/8a397cb0-6fc9-46da-9951-e508ed622ffb)
