### ISSUE TITLE
Hidden sections in Export / import data of Tenant/Settings

### ISSUE THREAD

**Issue by helakaraa** [MAIF/izanami#895]
In the Import data from V1 Izanami instance section, when clicking on "Import V1 data", the form opens but the other sections **Import data from another Izanami instance** and **Export data to transfer them to another instance** are hidden.

To make these sections visible again, the user must either cancel or submit the form.

Expected behavior: When the form is opened, all other sections should remain visible.

**Comment by ptitFicus** [comment]
I don't think it's really a bug since there is no scenario where we would like to open multiple import / export forms at the same time.
