### ISSUE TITLE
[webhooks] unable to select multiple Features or Projects

### ISSUE THREAD

**Issue by remi-picard** [MAIF/izanami#905]
Hello,

I'm using Docker `maif/izanami:2.5.0`.

In the form `Create new webhook`, it is impossible to add multiple features or projects. Only can be selected, even if the dropdown menu is OK. A click on the dropdown does nothing.

<img width="1439" alt="image" src="https://github.com/user-attachments/assets/e1e76c17-9f75-48ce-bd73-a27bb58e8c30">

<img width="1450" alt="image" src="https://github.com/user-attachments/assets/ebc53484-e1c8-4bdf-9d68-077c9b27fc66">

Regards,
Rémi PICARD

**Comment by ptitFicus** [comment]
Hi @remi-picard 

Thanks for reporting this, it's fixed in 2.6.1

Regards

Benjamin
